### ISSUE TITLE
read input from file

### ISSUE THREAD

**Issue by acoul** [mmitch/bgpgraph#1]
it would be nice to also have the option to read input from a file that contains the same info as the interactive vtysh extracts

great little tool, thank you

**Comment by mmitch** [comment]
Good idea!  I'll see if I find the time for that.
It is not as simple as ``vtysh with some parameters | vtysh_scanner`` because ``vtysh`` is called multiple times:
- once to get the neighbors
- then once for every neighbor
- finally once for the active routes

I'll have to come up with some sort of file or stream format that retains the info where the individual calls begin and and.
Or I'll have to pass the parsed data around.

**Comment by mmitch** [comment]
The easiest way to "split" the script would be to generate a .dot file instead of a PNG.  The .dot contains the combined parsed data, so it can be passed around as a single file.
Instead of the Perl Graphviz module, the standalone ``graphviz`` binary can be used.
Data aquisition (``vtysh`` calls) can be run on the router and the graphics stuff can be done somewhere else.

Alternatively there is a way to run ``vtysh`` remotely via ``ssh``.  I use this to collect data from my OpenWRT/LEDE router that has not enough space for any graphviz libraries.  This is already working, but it would need to be documented properly.

So  better ask the customer :-)
@acoul, what exactly is your use case?
Which problem do you want to solve by reading the data from a file?
Do you work with multiple systems?
Are you limited in what you can install on certain systems?

**Comment by mmitch** [comment]
I think you're right: a simple ``show ip bgp`` should be sufficient.
I have hacked together a working prototype and I don't see any difference in graphs of my networks (which only contain about 15 ASs, not nearly as impressive as your graphs).

Please check out the experimental oneshot branch: https://github.com/mmitch/bgpgraph/tree/oneshot
Note that you now have to give the local AS id via commandline parameter because there is no call to ``show ip bgp summary`` to detect it any more.

**Comment by mmitch** [comment]
The oneshot branch has been merged to master.
Please note that the script has been renamed to ``vtysh_bgp_to_dot``

**Comment by acoul** [comment]
Greetings Christian and thank you for your feedback, 

I have a silly question: why do we need the local_as in order to get a graph of the whole routing table?

**Comment by mmitch** [comment]
The local AS is needed because it is not included in ``vtysh -c 'show ip bgp'``. But your question was a good one, because I can make the parameter optional. If no local AS is given, the graph could default to a node named something like "you are here" :-)

Regarding your commandline:
* ``grep ^*`` is done internally by the script, but I understand you need it to make the rest of your filter work
* What does the ``grep " i"`` do?  I can see that some of my paths end in `` i`` while others end in `` ?``.  What is the difference?
* I don't understand what ``awk 'NF>1&&NF<28'`` is supposed to do.
* The ``grep ^[1-9]`` removes everything not starting with the digits 1-9. Disregardind the ``awk``, after the ``cut`` I have some paths in my output that are indented by one space.  These would be removed by the ``grep`` as well.  Is this intended?

Two things will be missing from after your filter:
* The ``Path`` headline that is used to find the column where the paths start (it is removed by your first ``grep``).  It can be re-added by a simple ``echo``.
* The line markers ``*`` for a path and ``*>`` for an active path are removed by your ``cut``.  They can be re-added by prepending every line with a ``* ``, but then the information whether a path is active is lost.

Long posting short, please try something like this:
```shell
(
  echo "   Path"
  vtysh -c "show ip bgp" | grep ^* | grep " i" | cut -c 1-3 -c 62-999 | awk 'NF>1&&NF<28' | grep ^...[1-9] | grep -v 22128
) | vtysh_bgp_to_dot
```

**Comment by acoul** [comment]
Greetings Christian,

I was able to get the [following output](http://dev.ozo.com/awmn.png)  by issuing:

**vtysh** -c "show ip bgp" | grep ^* | grep " i" | cut -c 1-3,62-999 | awk 'NF>2&&NF<29' | grep ^...[1-9]  | vtysh_bgp_to_dot 22128 | dot -Tpng > awmn.png

in my scenario, it would be nice to totally exclude the first node, ie 22128, and just have a picture of the rest of the network. think of it as excluding the local node and just printing the rest of the network.

**Comment by mmitch** [comment]
Hi Alexandros,
I have just added an option to exclude the local node: 5fb8fe7
To use this feature, just *don't* give a local AS on the commandline like this:
```shell
vtysh -c "show ip bgp" | grep ^* | grep " i" | cut -c 1-3,62-999 | awk 'NF>2&&NF<29' | grep ^...[1-9] | vtysh_bgp_to_dot | dot -Tpng > awmn.png
```

**Comment by acoul** [comment]
Hello Christian and thank you for your feedback,

I am now getting the following error either with or without (output is the same) providing a local AS:

`Error: <stdin>: syntax error in line 2 near ';'`

Here are the first lines of the vtysh_bgp_to_dot output:

> strict digraph {
>  ;
 > *;
 > *>;
 > 1;
 > 10030;

**Comment by mmitch** [comment]
I have recently added some test cases that take a fixed ``vtysh`` output, run it through ``vtysh_bgp_to_dot`` and check the generated dot file afterwards. These tests still run fine (see [here](https://travis-ci.org/mmitch/bgpgraph/builds)).
So either there are some corner cases that the tests are missing or something in your input is off.
I'd guess that there are some empty paths or lines because of your filtering.

Could you please give me the result of just
```shell
vtysh -c "show ip bgp" | grep ^* | grep " i" | cut -c 1-3,62-999 | awk 'NF>2&&NF<29' | grep ^...[1-9]
```
so I can have a look at what's going wrong?

**Comment by acoul** [comment]
I am sorry for the delay Christian. here is the dump you requested [spq_bgp_dump.txt](http://dev.ozo.com/spq_bgp_dump.txt)

**Comment by mmitch** [comment]
No problem about the delay.

I see something weird in your dump: Some lines start with ``*d`` instead of ``* `` or ``*>``. I don't know where this comes from, but it should be no problem.  Lines starting with ``*`` will be parsed and lines starting with ``*>`` will be considered active, so lines starting with ``*d`` will be considered inactive.
Looks strange, but does not hurt :-)

The actual problem seems to be that the ``echo "  Path"`` part from [this comment](https://github.com/mmitch/bgpgraph/issues/1#issuecomment-381402684) is missing

When I download your file and run ``./vtysh_bgp_to_dot < spq_bgp_dump.txt`` I get the same error as you.  The reason is that the script can't determine the column where the paths begin.

When I use ``(echo '   Path'; cat spq_bgp_dump.txt ) | ./vtysh_bgp_to_dot`` instead, everything looks fine.

Combining both the ``echo`` and your filter line, please try something like this:
```shell
(
  echo "   Path"
  vtysh -c "show ip bgp" | grep ^* | grep " i" | cut -c 1-3,62-999 | awk 'NF>2&&NF<29' | grep ^...[1-9]
) | vtysh_bgp_to_dot | dot -Tpng > awmn.png
```

**Comment by acoul** [comment]
Christian you are, once again, correct. I did miss the `echo " Path"`part. including it results in successful execution.  Everything works as a charm.

The '*d' reports the bgp dampened paths as this bgp collector also calculates flapped routes.

thanks so much for your time and your work contribution

cheers
